version: '3'
volumes:
  db_data:
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/var/www/app
  database:
    image: mysql/mysql-server:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: viwebsite_remote_server
      MYSQL_DATABASE: viwebsite_remote_server
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    # volumes:
      # - db_data:/var/lib/mysql/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5502:80"      
  nginx:
    image: nginx:1.15
    ports:
      - "5500:5500"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
